sudo: required
services:
  - docker

before_install:
  - docker build -t dockertester/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true dockertester/docker-react npm run test -- --coverage
